
pipeline {
    agent any

    stages {
        stage('CHECKOUT') {
            steps {
                echo 'Hello World'
                sh '''
                sleep 5
                ls -lrt
                '''
            }
            
        }
        
        stage('BUILD') {
            steps {
                sh " sleep 5"
                sh "ls -lrt "
                
                sh "pwd"
                
            }
            
        }
        
        stage('TEST') {
            steps {
                sh """
                echo this is test stage
                """
            }
            
        }
    }
}
